music/ahang/urls.py
from django.conf.urls import url
from . import views

app_name='music'
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^upload$', views.upload_music_form, name='upload'),
    url(r'^search$', views.search, name='search'),
    url(r'^signup$', views.register, name='register'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^logout$', views.logout_user, name='logout'),
    url(r'^edame/(?P<id>[0-9]{1,1000})*/$', views.ahang_detail, name='detail'),
]

# url(r'^(?P<ahang_esm>[\w+][^/]*)$', views.ahang_detail, name='detail'),
# r'^(?P<id>[0-9]{1,})+/(?P<ahang_esm>[\w+][^/]*)$'

music/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ahang.urls', namespace='music')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/templates/main/ahang_detail.html
{% extends 'main/index.html' %} {% block title %} {{title}} {% endblock %} {% block content %}

<div class="container-lg bg-dark text-white-50">
    <center>
{% comment %} showing messages to client if available {% endcomment %}
    {% if messages %}
        {% for message in messages %}
            {{message}}
        {% endfor %}
    {% endif %}
        <h1>{{ahang.author}}-{{ahang.ahang_esm}}</h1>
        <h2>{{ahang.updateDate|linebreaks}}</h2>
        <hr class="badge-primary col-sm-5">
        <h4>{{ahang.description|safe}}
            <br/>
            <p></p>

            <div class="containter-fluid">
                <audio controls="controls">
        <source src="{{ahang.ahang_file.url}}" >
        مرورگر شما از موسیقی پشتیبانی نمیکند یک مرورگر واقعی بگیرید :)
    </audio>
                <p></p>
                <a href={{ahang.ahang_file.url}} target="_blank" class="nav-link active" download>
        برای دانلود کلیک کنید
    </a>
            </div>
            <br>
            <p></p>
            <h2 style="direction: rtl;">  {{ comments.count }}   نظر موجود است</h2>
            <br><br>

          </div>
        </div>
        <h2 dir="rtl" style="text-align: right; margin-right: 100px;">نظرات</h2>
{% for comment in comments %}
      
<div class="text-center">             

  <strong><p> {{ comment.name }} </p><p> {{ comment.created_on }} </p></strong>
      <span class="text-decoration-none">  
        {{ comment.body }}
      </span>
      </div>

{% endfor %}


        <div class="col-md-8 card mb-4  mt-3 ">
          <div class="card-body">
            {% if new_comment %}
            <div class="alert alert-success" role="alert">
              نظر شما در حال ثبت است. ممنون از شکیبایی شما 
            </div>
            {% else %}
            <h3>نظر بدهید</h3>
            <form method="post" style="margin-top: 1.3em;">
              {% csrf_token %}
              {{ comment_form.as_p }}
              <button type="submit" class="btn btn-primary  btn-lg">ثبت</button>
            </form>
            <br><br>

                </span>


            </div>
    </center>
</div>
{% endif %}
{% endblock %}

music/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <title>
        {% block title %} {{title}} {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
        <a class="navbar-brand" href="{% url 'music:home' %}">nUmberX</a>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'music:home' %}"> خانه </a>
          </li>
          <li class="nav-item text-right">
            <a class="nav-link" href="{% url 'music:upload' %}"> آپلود آهنگ </a>
          </li>
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'music:register' %}"> ثبت نام </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'music:login' %}"> ورود </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'music:logout' %}"> خروج </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <div class="container-fluid" style="margin-top:80px">
    {% block content %}
    <div class="text-center">
        {% if messages %}
            {% for message in messages %}
                <span class="alert alert-primary">{{message}}</span>
            {% endfor %}
        {% endif %}
   </div>
    <div class="container-fluid bg-primary">
    <br />
    {% include 'main/search.html' %}


        {% for ahang in ahangha %}
        {% if ahang.isAgreed %}
        <ul class="list-group text-secondry">
            <li class="list-group-item text-center text-white bg-dark">{{ahang.author}}</li>
            <li class="list-group-item text-center text-white bg-dark">{{ahang.description|safe|truncatechars_html:120}}</li>
            <li class="list-group-item text-center text-white bg-dark"><a href="{{ahang.get_absolute_url}}"> ادامه مطلب </a></li>
        </ul>
        <br /> {% endif %}{% endfor %}
    </div>
    {% endblock %}
</body>
</html>

music/templates/main/login.html
{% extends 'main/index.html' %}
{% block title %}
    ورود                
{% endblock %}
{% block content %}

    <div class="container">
        <div class="align-content-center">
           <div class="text-center">
                {% if messages %}
                    {% for message in messages %}
                        <span class="alert alert-primary">{{message}}</span>
                    {% endfor %}
                {% endif %}
           </div>
            <form action="{% url 'music:login' %}" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">
                    ورود
                </button>
            </form>
        </div>
    </div>
{% endblock %}

music/templates/main/search.html
{% extends 'main/index.html' %}
{% block content %}
    <div class="container align-content-center text-center">

        <form action="{% url 'music:search' %}" method="get">
            <label for="q">
                جستجو
            </label>
            <input type="text" required name="q" value="{{ request.GET.q }}" class="form-control-sm">
            <br>
    
            <button type="submit" name="submitbutton" value="جستجو" class="btn btn-dark">
                Search
            </button>
            <br />
            <br />
        </form>
    </div>
   <div class="container-xl btn-group-lg">
    <div class="col-sm-7 bg-dark text-white"> 
    {% if submit == "جستجو" and request.GET.q != "" %}
        {% if result %}
            {% for r in result %}
                {{ r.author }}
                <br>
                {{ r.description|safe|truncatechars_html:100 }}
                <a href="{{ r.get_absolute_url }}"> ادامه</a>
            {% endfor %}
        {% else %}
            not found
        {% endif %}
    {% endif %}
        </div>
    </div>
{% endblock %}

music/templates/main/signup.html
{% extends 'main/index.html' %}
{% block title %}
    SignUp
{% endblock %}
{% block content %}
    <script>
        let warning = "توجه کنید که اهنگ هایی که دارای لایسینس هستند مورد تایید قرار نمیگیرند ممنون از شما دوست عزیز بابت توجه به این موضوع ."
        function licenceWarning(){
            alert(warning)
        }
    </script>
    <div class="container">
        <script>
            licenceWarning();
        </script>
        <div class="align-content-center">
           <div class="text-center">
                {% if messages %}
                    {% for message in messages %}
                        <span class="alert alert-primary">{{message}}</span>
                    {% endfor %}
                {% endif %}
           </div>
            <form action="{% url 'music:register' %}" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">
                    Register
                </button>
            </form>
        </div>
    </div>
{% endblock %}

music/templates/main/upload.html
{% extends 'main/index.html' %}
{% block title %}
آپلود آهنگ     
{% endblock title %}

{% block content %}
<script>
    msg = "توجه داشته باشید که آهنگ های پولی مورد تایید قرار نمیگیرند با تشکر از همکاری شما"
    function warning(licence_msg){
        confirm(licence_msg)
    }
    warning(msg);
</script>

{% if messages %}
   {% for m in messages %}
    <div class="container py-5">  
    <div class="alert alert-success">  
    <strong class="text-center text-capitalize">{{m}}</strong>
    </div>
    </div>  
    {% endfor %}
    {% endif %}
<div class="container-fluid align-content-center">
<form action="{% url 'music:upload' %}" method="POST" enctype="multipart/form-data"> 
{% csrf_token %}
{{form.as_p}}
<button type="submit" class="btn btn-lg btn-success">
    ارسال
</button>
</form>
{% endblock content %}